[package]
name = "stm32-support"
version = "0.1.0"
edition = "2021"

[features]

stm32f405rg = [
    "embassy-stm32/stm32f405rg",
    "embassy-stm32/time-driver-tim2",
]

stm32h743vi = [
    "embassy-stm32/stm32h743vi",
    "embassy-stm32/time-driver-tim2",
]

[dependencies]

defmt = "1.0.1"
static_cell = "2"
aligned = "0.4.2"

dshot-encoder = { git = "https://github.com/peterkrull/dshot-encoder" }

[dependencies.common]
path = "../../common"
default-features = false
features = ["defmt"]

[dependencies.embassy-futures]
git = "https://github.com/embassy-rs/embassy"
rev = "5bc8260"

[dependencies.embassy-executor]
git = "https://github.com/embassy-rs/embassy"
rev = "5bc8260"
features = [
    "platform-cortex-m",
    "executor-interrupt",
    "executor-thread",
]

[dependencies.embassy-stm32]
git = "https://github.com/embassy-rs/embassy"
rev = "5bc8260"
features = [
    "defmt",
    "exti",
]
