name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add thumbv6m-none-eabi target
      run: rustup target add thumbv6m-none-eabi
  
    - name: Add thumbv7m-none-eabihf target
      run: rustup target add thumbv7em-none-eabihf
  
    - name: Install dependencies
      run: cargo install flip-link

    - name: Build Holsatus Flight "common" library
      run: cargo build --manifest-path common/Cargo.toml --verbose

    - name: Run tests in Holsatus Flight "common" library
      run: cargo test --manifest-path common/Cargo.toml --verbose
